### ISSUE TITLE
information on ResNet models

### ISSUE THREAD

**Issue by akamaster** [yuhuixu1993/Trained-Rank-Pruning#1]
Hi, would you please share the number of parameters in achieved ResNet models for CIFAR10 using TRP? Namely for ResNet20 channel/spatial, ResNet32 channel/spatial.

Thanks!

**Comment by yuhuixu1993** [comment]
hi, about your questions, we add some tables in this project. Besides, we also provide results of ResNet50 on ImageNet.

**Comment by akamaster** [comment]
Thanks a lot!
